### ISSUE TITLE
Random Reddit post of the Day

### ISSUE THREAD

**Issue by ghost** [mindofbeholder/PickleBotJS#2]
Request a random Reddit post of the day from a certain pool of subreddits. Like !randred or !rred or even just !red. This could be automatic and done at 8 AM every morning, or it could be a physical call we can make.

**Comment by mindofbeholder** [comment]
@Silveramoon do you have a suggestion of subs or just pull one at random from /r/popular?

https://www.reddit.com/dev/api/

**Comment by ghost** [comment]
/r/pop works

**Comment by mindofbeholder** [comment]
Created it as a callable command.

**Comment by mindofbeholder** [comment]
Deployed to Picklebot
