### ISSUE TITLE
Subscript

### ISSUE THREAD

**Issue by ghost** [mindofbeholder/PickleBotJS#7]
I would like to have a way to make the subscript within a sentence. For example:

I'm not mad. {I'm mad} 
where {I'm mad} is subscript.

**Comment by mindofbeholder** [comment]
What would the actual **command** be for this?

**Comment by mindofbeholder** [comment]
Gonna run with **mini** for now.

**Comment by mindofbeholder** [comment]
Unfortunately I lied. There isn't support for all letters as subscript in Unicode and discord does not have support for HTML or Markdown subscript at this time. We'll have to revisit when discord adds support.
